# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def testing
  pod 'Quick'
  pod 'Nimble'
  pod 'RxTest'
  pod 'RxBlocking'
end

target 'NYTimes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  #Network
   pod 'Alamofire'
   pod 'Moya'
   pod 'Moya/RxSwift'
   pod 'MoyaSugar',
     :git => 'https://github.com/devxoul/MoyaSugar.git',
     :branch => 'master'
   pod 'MoyaSugar/RxSwift',
     :git => 'https://github.com/devxoul/MoyaSugar.git',
     :branch => 'master'
   pod 'Kingfisher'

   # Rx
   pod 'RxSwift'
   pod 'RxCocoa'
   pod 'RxSwiftExt', '~> 5'

   #Logging
   pod 'CocoaLumberjack/Swift'
   pod 'Then'
   
   #Lint
   pod 'SwiftLint'
  
   #Loader
   pod 'GeometricLoaders'

  
  # Pods for NYTimes

  target 'NYTimesTests' do
    inherit! :search_paths
    # Pods for testing
    testing
  end
  

  target 'NYTimesUITests' do
    # Pods for testing
    testing
  end

end
